# Generated by Django 5.0.7 on 2024-07-18 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_category_alter_product_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='has_discount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='has_gift',
        ),
        migrations.AddField(
            model_name='product',
            name='gift',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gift_for', to='products.product'),
        ),
    ]
