# Generated by Django 5.0.7 on 2024-07-18 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_product_has_discount_remove_product_has_gift_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gift_for', to='products.product'),
        ),
    ]
