# Generated by Django 5.0.7 on 2024-07-18 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_gift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_amount',
            field=models.IntegerField(default=0),
        ),
    ]
