# Generated by Django 3.2.12 on 2024-08-01 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='final_round_gear',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='fresh_off_the_line',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_amount',
            field=models.IntegerField(default=1),
        ),
    ]
