# Generated by Django 3.2.12 on 2024-07-26 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_amount',
            field=models.IntegerField(default=1),
        ),
    ]
